version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: teamfinder_db
    restart: always
    environment:
      POSTGRES_DB: teamfinder
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: